apiVersion: v2
appVersion: 2023.12.0
description: A Helm chart for deploying a Bitwarden instance on Kubernetes
home: https://github.com/bitwarden/helm-charts/tree/main/charts/self-host
icon: https://raw.githubusercontent.com/bitwarden/brand/master/icons/icon-square.svg
maintainers:
- name: dept-devops
name: self-host
type: application
version: 0.1.14-Beta
