apiVersion: v2
appVersion: 2025.8.0
description: A Helm chart for deploying a Bitwarden instance on Kubernetes
home: https://github.com/bitwarden/helm-charts/tree/main/charts/self-host
icon: https://raw.githubusercontent.com/bitwarden/brand/master/icons/icon-square.svg
maintainers:
- name: bitwarden
name: self-host
type: application
version: 1.0.0
