name: Build and push kubectl image

on:
  workflow_dispatch:
    inputs:
      kubectl_version:
        description: "kubectl version"
        required: false
        default: "1.34"
      push:
        description: "Push image to GitHub Container Registry"
        required: false
        type: boolean
        default: true

jobs:
  build-docker:
    name: Build and push kubectl Docker image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout Bitnami repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: bitnami/containers
          ref: main
          persist-credentials: false

      - name: Login to GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push kubectl image
        id: build-docker
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        env:
          _KUBECTL_VERSION: ${{ inputs.kubectl_version }}
          _INPUT_PUSH: ${{ inputs.push }}
        with:
          context: ./bitnami/kubectl/${_KUBECTL_VERSION}/debian-12
          file: ./bitnami/kubectl/${_KUBECTL_VERSION}/debian-12/Dockerfile
          push: ${_INPUT_PUSH}
          tags: |
            ghcr.io/bitwarden/helm-charts/kubectl:latest
            ghcr.io/bitwarden/helm-charts/kubectl:${_KUBECTL_VERSION}
