name: Lint sm-operator

on:
  pull_request:
    paths:
      - 'charts/sm-operator/**'
  push:
    branches:
      - main
    paths:
      - 'charts/sm-operator/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-sm-operator:
    name: Lint sm-operator chart
    uses: ./.github/workflows/_lint_chart.yml
    with:
      chart_name: sm-operator
