# This workflow is intended to be run when we need to test the helm charts on the PR target.
# This workflow will run in the context of the target of the PR and have access to secrets.
# This should only be done after reviewing the PR to ensure that no malicious code has been introduced,
# as it could allow the code on the forked branch to have access to workflow secrets. 

name: Test Helm Charts on PR Target

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths:
      - 'charts/**'
      - '!*.md'
      - '!*.txt'

defaults:
  run:
    shell: bash

jobs:
  check-run:
    permissions:
      contents: read
    name: Check PR run
    uses: bitwarden/gh-actions/.github/workflows/check-run.yml@main

  run-self-host-workflow:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    name: Self Host
    needs: check-run
    if: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
    uses: ./.github/workflows/self-host.yml
    secrets:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}

  run-sm-operator-workflow:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    name: SM Operator
    needs: check-run
    if: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
    uses: ./.github/workflows/sm-operator.yml
    secrets:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
